# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f63042a703399d64e9d4875d6822bfb9d627001e48db1906d0d271100dd8a459df08c8c56413bace925d57f5468c4035eecdb785680f48e39339275e077538b

test:
  secret_key_base: 73f1d8bd35b986ba5e47621738c0a124085071003c0b32e37b1021bb11efa5923ee99e2278ff799d3fe2d1e27a3f5aedda0ab37339a8a438843f1f8d32c2d1af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
